### ISSUE TITLE
How can i  automatically add the members accounts list in dyanamodb table

### ISSUE THREAD

**Issue by itsgsurya** [aws-samples/aws-security-hub-cross-account-controls-disabler#3]
hello, 
  We have more than 500 accounts and it will grow as well. Is there any possibility to add the member's accounts list automatically in dynamoDB table?
 
how can I disable the below Security hub check-in around 500 accounts,  I mean based on your solution?  
  ex: Ensure multi-factor authentication (MFA) is enabled for all IAM users that have a console password

Thanks,
Surya

**Comment by ahmedqe** [comment]
Hi @itsgsurya,

The DynamoDB table is meant for adding exceptions (either accounts or controls). In other words, you can add account x in the table to make sure control y is not disabled for that account. I don't see a use case to add the 500 accounts in the table (for exception).

However, in order to add multiple items to a table automatically, you can write a Lambda function that retrieves the account ids of all member accounts and update the DDB table. This is out of the scope of this solution though.

In order to disable a control in the 500 accounts, you just need to disable that control from the security hun administrator account. You will see the effect in few seconds if you enable the CW event in the solution (disabled by default) or wait 1 day (the duration for the other scheduled CW event) to see the effect.

If you need to disable it only for 499 accounts, add the remaining account in the table as written in the README file.

Best,
Ahmed

**Comment by itsgsurya** [comment]
Hello Ahmed,
Thx for your clarification!   My requirement is to disable certain controls in my dev environments. I have implemented your solution It's working fine but there are some strange issues in the Controls Exception database. 
 I have put a few control exceptions for my dev environment,  In a few aws accounts, the script disabled the wrong controls which are not in the exceptions database.

I have attached screenshots for your reference, Any suggestions for me
![Screen Shot 2022-03-31 at 13 52 43](https://user-images.githubusercontent.com/25867181/161062988-8a29139b-aea5-4771-9288-cab6567d8436.png)
![Screen Shot 2022-03-31 at 13 51 59](https://user-images.githubusercontent.com/25867181/161063054-4e8f9caa-4d66-46d2-a8af-dc2d8d1da3b1.png)
![Screen Shot 2022-03-31 at 15 15 02](https://user-images.githubusercontent.com/25867181/161063307-00b999e8-cd1b-44ec-988d-17d1459b0186.png)
.

**Comment by ahmedqe** [comment]
@itsgsurya from the screenshots you attached, it seems like everything is working as expected. I believe there is a misunderstanding here. Please follow the example in the [README](https://github.com/aws-samples/aws-security-hub-cross-account-controls-disabler/blob/main/README.md). The solution can be used to both enable and disable controls and you can provide exceptions for either way. In the screenshots you added the accounts IDs in the disabled column. Therefore, if you enable that control (if it is previously disabled) it will remain disabled in those accounts. But if the control is enabled state and you disable it then the code checks for the entries in the `Enabled` column not the other one. The controls will definitely be disabled because you didn't add any exception. I hope this answers your question. I will resolve the issue for now.

Best,
Ahmed

**Comment by itsgsurya** [comment]
My scenario here. example :

I have added accounts "111111111111", "222222222222" both are in disabled Colum in dynamodb.  Actually, the solution disabled the right controls for account "111111111111",  but for account "222222222222"   it disabled the wrong controls which are not in the exceptions database.    ex: redshift.1  control
You can find the info in my previous screenshots.

**Comment by ahmedqe** [comment]
@itsgsurya when did you deploy the solution? There was a bug fix few weeks ago.

**Comment by itsgsurya** [comment]
@ahmedqe It's the latest one. I am the guy who informed you about  Pagination-error  :)  and deployed the same changes even to my environment.

**Comment by ahmedqe** [comment]
@itsgsurya can you paste the table content as JSON like the example in the README? I can't get enough details from the screenshots

**Comment by itsgsurya** [comment]
I have attached my dynamodb screenshot . 
![Screen Shot 2022-03-31 at 16 18 58](https://user-images.githubusercontent.com/25867181/161079691-f3d7bf08-3855-41bf-a711-a247b8ed3ad3.png)
